sudo: required
services:
  - docker

before_install:
  - docker build -t lucasalmada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lucasalmada/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-516054473551"
  bucket_path: "docker-react"
  on:
    branch: master
  acess_key_id: $AWS_ACESS_KEY
  secret_acess_key: "$AWS_SECRET_KEY"
